### PR TITLE
Feature/extend commands

### PR DESCRIPTION
**Pull request by juliomotol**
This PR Closes https://github.com/Artem-Schander/L5Modular/issues/46

### CODE REVIEW

**Comment by Artem-Schander** [comment]
Nice. Thanks for the effort :)
It would be nice if you could add a few tests to some make commands.
See [coverage.zip](https://github.com/Artem-Schander/L5Modular/files/4334219/coverage.zip)

In the meantime I will add the config and complete `ModuleMakeCommand.php` with the new components.

**Comment by juliomotol** [comment]
Got this, How do I check for this?

**Comment by Artem-Schander** [comment]
If you have Xdebug installed you should get the contents of the zip by default after running the tests. They are located in the `build/coverage` folder.

The output of `php -v` should look something like this
```bash
PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Dec 18 2019 14:48:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
    with blackfire v1.29.6~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

Alternatively you could see a less informative output in the [travis build log](https://travis-ci.com/github/Artem-Schander/L5Modular/jobs/298292269)

**Comment by juliomotol** [comment]
All good, I don't know why the checks failed on this one though...

**Comment by Artem-Schander** [comment]
Linux filesystem is case sensitive. 
https://github.com/Artem-Schander/L5Modular/commit/1fc69951c822132b944ea10d48bd3f57541d08f3

**Comment by Artem-Schander** [comment]
Many thanks for your work. I will let you know when the v2 release is ready.
Closes #42 and #46

**Comment by Artem-Schander** [comment]
There seems to be an issue with the `MigrateMakeCommand`.
Bildschirmfoto 2020-03-15 um 18 52 06

Do you have an idea how this could be fixed? It does not look like the issue comes from your code but from the extended class.

You can reproduce it by creating a new laravel project, require "artem-schander/l5-modular": "dev-release/2.0.0" and run `php artisan`

**Comment by juliomotol** [comment]
I'll look into this later in the day

**Comment by Artem-Schander** [comment]
I think I have a solution. If you're trying to figure it out too, you can stop it for now.

**Comment by juliomotol** [comment]
Oh shoot, forgot about this sorry. feel free to hit me up if you need any kind of help.

**Comment by Artem-Schander** [comment]
@juliomotol 
The v2 is released now.
Thanks again for your work. I certainly wouldn't have had enough time to take the big step and release the v2. If it means something to you, I could mention you as a contributor somehow.

**Comment by juliomotol** [comment]
Awesome! A mention would great! It'll be the first time for me.

**Comment by Artem-Schander** [comment]
@all-contributors please add @juliomotol for extending commands

**Comment by Artem-Schander** [comment]
@all-contributors please add @juliomotol for code

**Pull request merged**
